// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DGC.eKYC.Dal.Models;

public partial class Client
{
    public int Id { get; set; }

    public int OrgId { get; set; }

    public string ClientName { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<EkycTransaction> EkycTransactions { get; set; } = new List<EkycTransaction>();

    public virtual Organization Org { get; set; }
}